# Directory where the input week directories are located
input: "data/MiSeq_data"

# Directory where the output results will be written
output: "results/MiSeq_data"

# The length to which the reads are trimmed to 
max_read_length: 180
