run_modules:
  - fastqc
  - fastp

extra_fn_clean_exts:
  - '_001'

top_modules:
  - "fastqc":
      name: "FastQC (pre-Trimming)"
      path_filters:
        - "*001_fastqc.zip"
  - "fastp"
  - "fastqc":
      name: "FastQC (post-Trimming)"
      path_filters:
        - "*.trim_fastqc.zip"
